/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interrogate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interrogate Get */
        get: operations["interrogate_get_interrogate_get"];
        put?: never;
        /** Interrogate Post */
        post: operations["interrogate_post_interrogate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interrogate/{alias}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interrogate Post */
        post: operations["interrogate_post_interrogate__alias__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kaloscope/infer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kaloscope Infer */
        post: operations["kaloscope_infer_kaloscope_infer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtistMatch */
        ArtistMatch: {
            /** Name */
            name: string;
            /** Score */
            score: number;
        };
        /** Body_interrogate_post_interrogate__alias__post */
        Body_interrogate_post_interrogate__alias__post: {
            /** File */
            file: string[];
        };
        /** Body_interrogate_post_interrogate_post */
        Body_interrogate_post_interrogate_post: {
            /** File */
            file: string[];
        };
        /** Body_kaloscope_infer_kaloscope_infer_post */
        Body_kaloscope_infer_kaloscope_infer_post: {
            /** File */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Git Sha */
            git_sha?: string | null;
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /** InterrogateResult */
        InterrogateResult: {
            /**
             * Artist
             * @default {}
             */
            artist: {
                [key: string]: number;
            };
            /**
             * Character
             * @default {}
             */
            character: {
                [key: string]: number;
            };
            /**
             * Copyright
             * @default {}
             */
            copyright: {
                [key: string]: number;
            };
            /**
             * Meta
             * @default {}
             */
            meta: {
                [key: string]: number;
            };
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Rating
             * @default {}
             */
            rating: {
                [key: string]: number;
            };
            /** Tag String */
            tag_string: string;
            /** Tags */
            tags: {
                [key: string]: number;
            };
        };
        /** KaloscopeResponse */
        KaloscopeResponse: {
            /** Artists */
            artists: components["schemas"]["ArtistMatch"][];
            /**
             * Model
             * @default kaloscope-2.0
             */
            model: string;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Default Character Threshold */
            default_character_threshold: number;
            /** Default Threshold */
            default_threshold: number;
            /**
             * Default Thresholds
             * @default {}
             */
            default_thresholds: {
                [key: string]: number;
            };
            /** Description */
            description: string;
            /** Family */
            family: string;
            /** Gated */
            gated: boolean;
            /** Group */
            group: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Loaded */
            loaded: boolean;
            /** Recommended */
            recommended: boolean;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /** Models */
            models: components["schemas"]["ModelInfo"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    interrogate_get_interrogate_get: {
        parameters: {
            query: {
                url: string[];
                /** @description Model id from /models */
                model?: string | null;
                threshold?: number | null;
                character_threshold?: number | null;
                copyright_threshold?: number | null;
                artist_threshold?: number | null;
                meta_threshold?: number | null;
                rating_threshold?: number | null;
                use_spaces?: boolean;
                use_escape?: boolean;
                include_ranks?: boolean;
                score_descend?: boolean;
                /** @description Optional trigger word to prepend to tags */
                trigger_word?: string;
                /** @description Randomize tag order (useful for training) */
                random_order?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterrogateResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interrogate_post_interrogate_post: {
        parameters: {
            query?: {
                alias?: string | null;
                /** @description Model id from /models */
                model?: string | null;
                threshold?: number | null;
                character_threshold?: number | null;
                copyright_threshold?: number | null;
                artist_threshold?: number | null;
                meta_threshold?: number | null;
                rating_threshold?: number | null;
                use_spaces?: boolean;
                use_escape?: boolean;
                include_ranks?: boolean;
                score_descend?: boolean;
                output_format?: "json" | "zip";
                /** @description Optional trigger word to prepend to tags */
                trigger_word?: string;
                /** @description Randomize tag order (useful for training) */
                random_order?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_interrogate_post_interrogate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterrogateResult"][];
                    "application/zip": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interrogate_post_interrogate__alias__post: {
        parameters: {
            query?: {
                /** @description Model id from /models */
                model?: string | null;
                threshold?: number | null;
                character_threshold?: number | null;
                copyright_threshold?: number | null;
                artist_threshold?: number | null;
                meta_threshold?: number | null;
                rating_threshold?: number | null;
                use_spaces?: boolean;
                use_escape?: boolean;
                include_ranks?: boolean;
                score_descend?: boolean;
                output_format?: "json" | "zip";
                /** @description Optional trigger word to prepend to tags */
                trigger_word?: string;
                /** @description Randomize tag order (useful for training) */
                random_order?: boolean;
            };
            header?: never;
            path: {
                alias: string | null;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_interrogate_post_interrogate__alias__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterrogateResult"][];
                    "application/zip": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kaloscope_infer_kaloscope_infer_post: {
        parameters: {
            query?: {
                /** @description Number of top artist matches to return */
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_kaloscope_infer_kaloscope_infer_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KaloscopeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
}
